### ISSUE TITLE
IS there a way to build the app without enrollment in apple developer program ? 

### ISSUE THREAD

**Issue by OmarBoshra** [Appollo-CLI/Appollo#11]
I don't want to pay the 99 dollars now and don't have a mac for Xcode , Is there a way to build the app without enrollment in apple developer program ?

**Comment by SOG-web** [comment]
Testing it on simulator will still work for me, whenever I am ready to publish to store I will enroll for there dev program.

Thanks so much for this effort, but when can we expect the new version

**Comment by JulienP95** [comment]
Hey, you can expect the new version for the end of march. We are currently working on it!

**Comment by maxcmoi89** [comment]
@OmarBoshra , @SOG-web , this is now possible since release 1.0.0 of Appollo which has been released today.

**Comment by SOG-web** [comment]
Thanks so much

**Comment by OmarBoshra** [comment]
I have a windows machine though and have an ipad , is there no way to build on the ipad from windows machine
