### ISSUE TITLE
Can't complete appollo apple add command

### ISSUE THREAD

**Issue by ozaner** [Appollo-CLI/Appollo#12]
When trying to link my apple developer account with the appollo command line tool, I get the following error after passing it my private key file:

```
Error: for apple_id - ['Ensure this field has no more than 10 characters.']
```

Here's a screenshot:

![Capture](https://user-images.githubusercontent.com/56015962/224192549-e09cd36f-3cee-4ade-b8c5-a2f84a1cb1bc.PNG)

The "apple id" field is the email associated with my apple developer account right?

**Comment by ozaner** [comment]
My fault, I was using the wrong apple ID.

**Comment by JulienP95** [comment]
Hello Ozaner,

Like you probably figured it out, the Apple ID is actually the Team ID on your Apple developer account.

https://appollo.readthedocs.io/en/master/tutorial/2_configure_app_store_connect.html#step-3-complete-the-required-missing-information-and-where-to-find-it
