### ISSUE TITLE
How can we contribute to the available instance

### ISSUE THREAD

**Issue by SOG-web** [Appollo-CLI/Appollo#15]
I got this response No instance available at the moment. Waiting for one to be free...

How can we contribute to the server or how can we host our custom server.

I really appreciate this work and effort and i love it

**Comment by tchavetdeuse** [comment]
Hi, we currently have a few mac servers on which the VMs are run. Unfortunately if they are all taken you have to wait until one is free, but there are more slots available for non-configuration builds as they take less resources and time. We are monitoring how much they are used and will add new macs if there often are too many builds waiting.
Self hosting is unfortunately not possible, as you need a mac server for that.
