### ISSUE TITLE
Error when generating ad-hoc build

### ISSUE THREAD

**Issue by AndresArias09** [Appollo-CLI/Appollo#17]
Hi everyone,

I got a problem when i try yo generate a new build of my flutter project with appollo.

When executing command _appollo build start: ad-hoc_, i got a message saying my build failed, and here is the logs:

Build started at 2023-03-27 15:16:29.438368+00:00
----- Certificate keychain importation -----
1 certificate imported.
1 key imported.
keychain: "/Users/appollo/Library/Keychains/appollo.keychain-db"
version: 512
class: 0x00000010
attributes:
    0x00000000 <uint32>=0x00000010
    0x00000001 <blob>="Imported Private Key"
    0x00000002 <blob>=<NULL>
    0x00000003 <uint32>=0x00000001
    0x00000004 <uint32>=0x00000000
    0x00000005 <uint32>=0x00000000
    0x00000006 <blob>=0x3C76833BA30920D5E27D72CAB957A65008009290  "<v\203;\243\011 \325\342}r\312\271W\246P\010\000\222\220"
    0x00000007 <blob>=<NULL>
    0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
    0x00000009 <uint32>=0x0000002A  "\000\000\000*"
    0x0000000A <uint32>=0x00000800
    0x0000000B <uint32>=0x00000800
    0x0000000C <blob>=0x0000000000000000
    0x0000000D <blob>=0x0000000000000000
    0x0000000E <uint32>=0x00000001
    0x0000000F <uint32>=0x00000001
    0x00000010 <uint32>=0x00000001
    0x00000011 <uint32>=0x00000000
    0x00000012 <uint32>=0x00000001
    0x00000013 <uint32>=0x00000001
    0x00000014 <uint32>=0x00000001
    0x00000015 <uint32>=0x00000001
    0x00000016 <uint32>=0x00000001
    0x00000017 <uint32>=0x00000001
    0x00000018 <uint32>=0x00000001
    0x00000019 <uint32>=0x00000001
    0x0000001A <uint32>=0x00000001
----- Provisioning profile importation -----
----- Unzipping sources -----
----- Git patch initialization -----
Initialized empty Git repository in /Users/appollo/Documents/app/.git/
 Initial
 191 files changed, 13644 insertions(+)
 create mode 100644 .env
 create mode 100644 .gitignore
 create mode 100644 .metadata
 create mode 100644 README.md
 create mode 100644 analysis_options.yaml
 create mode 100644 android/.gitignore
 create mode 100644 android/app/build.gradle
 create mode 100644 android/app/src/debug/AndroidManifest.xml
 create mode 100644 android/app/src/main/AndroidManifest.xml
 create mode 100644 android/app/src/main/kotlin/com/example/cardio_movil_app/MainActivity.kt
 create mode 100644 android/app/src/main/res/drawable-v21/launch_background.xml
 create mode 100644 android/app/src/main/res/drawable/launch_background.xml
 create mode 100644 android/app/src/main/res/mipmap-hdpi/ic_launcher.png
 create mode 100644 android/app/src/main/res/mipmap-mdpi/ic_launcher.png
 create mode 100644 android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
 create mode 100644 android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
 create mode 100644 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
 create mode 100644 android/app/src/main/res/values-night/styles.xml
 create mode 100644 android/app/src/main/res/values/styles.xml
 create mode 100644 android/app/src/profile/AndroidManifest.xml
 create mode 100644 android/build.gradle
 create mode 100644 android/gradle.properties
 create mode 100644 android/gradle/wrapper/gradle-wrapper.properties
 create mode 100644 android/settings.gradle
 create mode 100644 icons/cardio_launcher_icon.png
 create mode 100644 images/Corazon-01.jpg
 create mode 100644 images/Corazon-02.jpg
 create mode 100644 images/Corazon.jpg
 create mode 100644 images/back-arrow.png
 create mode 100644 images/home.png
 create mode 100644 images/home_screen/logo-asistente-linea.png
 create mode 100644 images/home_screen/logo-autorizaciones-medicas.png
 create mode 100644 images/home_screen/logo-califica.png
 create mode 100644 images/home_screen/logo-citas.png
 create mode 100644 images/home_screen/logo-inicio.png
 create mode 100644 images/home_screen/logo-medicamentos.png
 create mode 100644 images/home_screen/logo-mi-salud.png
 create mode 100644 images/home_screen/logo-pagos.png
 create mode 100644 images/home_screen/logo-tele-m.png
 create mode 100644 images/home_screen/logo-usuario.png
 create mode 100644 images/icono_seguimiento_medicamentos.png
 create mode 100644 images/info_medicamentos.png
 create mode 100644 images/laboratorios.png
 create mode 100644 images/logo.png
 create mode 100644 images/logo_anterior.png
 create mode 100644 images/logos_cita.png
 create mode 100644 images/logos_dosis.png
 create mode 100644 images/logos_eventos.png
 create mode 100644 images/logos_laboratorio.png
 create mode 100644 images/screen_home.jpg
 create mode 100644 images/signos_alarma.png
 create mode 100644 ios/.gitignore
 create mode 100644 ios/Flutter/AppFrameworkInfo.plist
 create mode 100644 ios/Flutter/Debug.xcconfig
 create mode 100644 ios/Flutter/Release.xcconfig
 create mode 100644 ios/Runner.xcodeproj/project.pbxproj
 create mode 100644 ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
 create mode 100644 ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
 create mode 100644 ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
 create mode 100644 ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
 create mode 100644 ios/Runner.xcworkspace/contents.xcworkspacedata
 create mode 100644 ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
 create mode 100644 ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
 create mode 100644 ios/Runner/AppDelegate.swift
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
 create mode 100644 ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
 create mode 100644 ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
 create mode 100644 ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
 create mode 100644 ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
 create mode 100644 ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
 create mode 100644 ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
 create mode 100644 ios/Runner/Base.lproj/LaunchScreen.storyboard
 create mode 100644 ios/Runner/Base.lproj/Main.storyboard
 create mode 100644 ios/Runner/Info.plist
 create mode 100644 ios/Runner/Runner-Bridging-Header.h
 create mode 100644 lib/Models/api_response.dart
 create mode 100644 lib/Models/calendario.dart
 create mode 100644 lib/Models/event.dart
 create mode 100644 lib/Models/infoDosis.dart
 create mode 100644 lib/Models/medicamento.dart
 create mode 100644 lib/Models/paciente.dart
 create mode 100644 lib/Models/si_no.dart
 create mode 100644 lib/Models/sintoma.dart
 create mode 100644 lib/Models/tipo_documento.dart
 create mode 100644 lib/Models/user.dart
 create mode 100644 lib/Screens/CitasMedicas.dart
 create mode 100644 lib/Screens/DatosLaboratorio.dart
 create mode 100644 lib/Screens/Home.dart
 create mode 100644 lib/Screens/Index.dart
 create mode 100644 lib/Screens/InfoDosis.dart
 create mode 100644 lib/Screens/Login.dart
 create mode 100644 lib/Screens/PassForgotten.dart
 create mode 100644 lib/Screens/Register.dart
 create mode 100644 lib/Screens/SeguimientoMedicamentos.dart
 create mode 100644 lib/Screens/SignosAlarma.dart
 create mode 100644 lib/Screens/Usuario.dart
 create mode 100644 lib/Screens/calendario_eventos.dart
 create mode 100644 lib/Widgets/router.dart
 create mode 100644 lib/Widgets/side_menu.dart
 create mode 100644 lib/components/error_dialog.dart
 create mode 100644 lib/components/get_photo_dialog.dart
 create mode 100644 lib/flutter_flow/flutter_flow_drop_down.dart
 create mode 100644 lib/flutter_flow/flutter_flow_theme.dart
 create mode 100644 lib/flutter_flow/flutter_flow_util.dart
 create mode 100644 lib/flutter_flow/flutter_flow_widgets.dart
 create mode 100644 lib/main.dart
 create mode 100644 lib/repository/FileRepository.dart
 create mode 100644 lib/services/auth.dart
 create mode 100644 lib/services/calendario_service.dart
 create mode 100644 lib/services/medicamento_service.dart
 create mode 100644 lib/services/par_service.dart
 create mode 100644 lib/services/user_service.dart
 create mode 100644 lib/util/file_extensions.dart
 create mode 100644 linux/.gitignore
 create mode 100644 linux/CMakeLists.txt
 create mode 100644 linux/flutter/CMakeLists.txt
 create mode 100644 linux/flutter/generated_plugin_registrant.cc
 create mode 100644 linux/flutter/generated_plugin_registrant.h
 create mode 100644 linux/flutter/generated_plugins.cmake
 create mode 100644 linux/main.cc
 create mode 100644 linux/my_application.cc
 create mode 100644 linux/my_application.h
 create mode 100644 macos/.gitignore
 create mode 100644 macos/Flutter/Flutter-Debug.xcconfig
 create mode 100644 macos/Flutter/Flutter-Release.xcconfig
 create mode 100644 macos/Flutter/GeneratedPluginRegistrant.swift
 create mode 100644 macos/Runner.xcodeproj/project.pbxproj
 create mode 100644 macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
 create mode 100644 macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
 create mode 100644 macos/Runner.xcworkspace/contents.xcworkspacedata
 create mode 100644 macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
 create mode 100644 macos/Runner/AppDelegate.swift
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
 create mode 100644 macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
 create mode 100644 macos/Runner/Base.lproj/MainMenu.xib
 create mode 100644 macos/Runner/Configs/AppInfo.xcconfig
 create mode 100644 macos/Runner/Configs/Debug.xcconfig
 create mode 100644 macos/Runner/Configs/Release.xcconfig
 create mode 100644 macos/Runner/Configs/Warnings.xcconfig
 create mode 100644 macos/Runner/DebugProfile.entitlements
 create mode 100644 macos/Runner/Info.plist
 create mode 100644 macos/Runner/MainFlutterWindow.swift
 create mode 100644 macos/Runner/Release.entitlements
 create mode 100644 pubspec.lock
 create mode 100644 pubspec.yaml
 create mode 100644 test/widget_test.dart
 create mode 100644 web/favicon.png
 create mode 100644 web/icons/Icon-192.png
 create mode 100644 web/icons/Icon-512.png
 create mode 100644 web/icons/Icon-maskable-192.png
 create mode 100644 web/icons/Icon-maskable-512.png
 create mode 100644 web/index.html
 create mode 100644 web/manifest.json
 create mode 100644 windows/.gitignore
 create mode 100644 windows/CMakeLists.txt
 create mode 100644 windows/flutter/CMakeLists.txt
 create mode 100644 windows/flutter/generated_plugin_registrant.cc
 create mode 100644 windows/flutter/generated_plugin_registrant.h
 create mode 100644 windows/flutter/generated_plugins.cmake
 create mode 100644 windows/runner/CMakeLists.txt
 create mode 100644 windows/runner/Runner.rc
 create mode 100644 windows/runner/flutter_window.cpp
 create mode 100644 windows/runner/flutter_window.h
 create mode 100644 windows/runner/main.cpp
 create mode 100644 windows/runner/resource.h
 create mode 100644 windows/runner/resources/app_icon.ico
 create mode 100644 windows/runner/runner.exe.manifest
 create mode 100644 windows/runner/utils.cpp
 create mode 100644 windows/runner/utils.h
 create mode 100644 windows/runner/win32_window.cpp
 create mode 100644 windows/runner/win32_window.h
----- Flutter preparation -----

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter pub get" in flutter_tools...
Resolving dependencies in ../../../../Volumes/My Shared Files/flutter/packages/flutter_tools...
  _fe_analyzer_shared 50.0.0 (58.0.0 available)
  analyzer 5.2.0 (5.10.0 available)
  archive 3.3.2 (3.3.6 available)
  args 2.3.1 (2.4.0 available)
  async 2.10.0 (2.11.0 available)
  built_value 8.4.2 (8.4.4 available)
  checked_yaml 2.0.1 (2.0.2 available)
  collection 1.17.0 (1.17.1 available)
  completion 1.0.0 (1.0.1 available)
  coverage 1.6.1 (1.6.3 available)
  dds 2.5.0 (2.7.6 available)
  dds_service_extensions 1.3.1 (1.3.3 available)
  devtools_shared 2.18.0 (2.22.2 available)
  dwds 16.0.2+1 (18.0.2 available)
  fixnum 1.0.1 (1.1.0 available)
  frontend_server_client 3.1.0 (3.2.0 available)
  html 0.15.1 (0.15.2 available)
  intl 0.17.0 (0.18.0 available)
  io 1.0.3 (1.0.4 available)
  js 0.6.5 (0.6.7 available)
  json_annotation 4.7.0 (4.8.0 available)
  logging 1.1.0 (1.1.1 available)
  matcher 0.12.13 (0.12.15 available)
  meta 1.8.0 (1.9.1 available)
  mime 1.0.2 (1.0.4 available)
  multicast_dns 0.3.2+2 (0.3.2+3 available)
  native_stack_traces 0.5.2 (0.5.5 available)
  node_preamble 2.0.1 (2.0.2 available)
  path 1.8.2 (1.8.3 available)
  petitparser 5.1.0 (5.3.0 available)
  pubspec_parse 1.2.1 (1.2.2 available)
  source_maps 0.10.11 (0.10.12 available)
  sse 4.1.1 (4.1.2 available)
  test 1.22.0 (1.24.0 available)
  test_api 0.4.16 (0.5.0 available)
  test_core 0.4.20 (0.5.0 available)
  vm_service 9.4.0 (11.3.0 available)
  web_socket_channel 2.2.0 (2.3.0 available)
  webdriver 3.0.1 (3.0.2 available)
Got dependencies in ../../../../Volumes/My Shared Files/flutter/packages/flutter_tools!
Cleaning Xcode workspace...                                         3.2s
Cleaning Xcode workspace...                                      2,287ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in app...
Resolving dependencies...
  args 2.3.1 (2.4.0 available)
> async 2.10.0 (was 2.8.2) (2.11.0 available)
> boolean_selector 2.1.1 (was 2.1.0)
  cached_network_image 3.2.1 (3.2.3 available)
  cached_network_image_platform_interface 1.0.0 (2.0.0 available)
  cached_network_image_web 1.0.1 (1.0.2 available)
> characters 1.2.1 (was 1.2.0) (1.3.0 available)
> clock 1.1.1 (was 1.1.0)
> collection 1.17.0 (was 1.16.0) (1.17.1 available)
  convert 3.1.0 (3.1.1 available)
  cool_alert 1.1.0 (2.0.1 available)
> fake_async 1.3.1 (was 1.3.0)
  file_picker 3.0.4 (5.2.6 available)
  flutter_form_builder 7.7.0 (7.8.0 available)
  flutter_launcher_icons 0.9.3 (0.12.0 available)
  font_awesome_flutter 10.1.0 (10.4.0 available)
  form_builder_validators 8.4.0 (8.5.0 available)
  google_fonts 3.0.1 (4.0.3 available)
  image 3.3.0 (4.0.15 available)
  image_picker_android 0.8.6+1 (0.8.6+6 available)
  image_picker_ios 0.8.6+9 (0.8.7+1 available)
  intl 0.17.0 (0.18.0 available)
> js 0.6.5 (was 0.6.4) (0.6.7 available)
  json_path 0.4.1 (0.5.0 available)
  lottie 1.4.2 (2.3.0 available)
> matcher 0.12.13 (was 0.12.11) (0.12.15 available)
> material_color_utilities 0.2.0 (was 0.1.4) (0.3.0 available)
> meta 1.8.0 (was 1.7.0) (1.9.1 available)
> path 1.8.2 (was 1.8.1) (1.8.3 available)
  path_provider 2.0.13 (2.0.14 available)
  path_provider_foundation 2.1.3 (2.2.0 available)
  petitparser 5.0.0 (5.3.0 available)
  pointycastle 3.6.2 (3.7.2 available)
  shared_preferences 2.0.15 (2.0.20 available)
> source_span 1.9.1 (was 1.8.2)
  sqflite 2.0.3+1 (2.2.6 available)
  sqflite_common 2.4.0 (2.4.3 available)
> stack_trace 1.11.0 (was 1.10.0)
> stream_channel 2.1.1 (was 2.1.0)
> string_scanner 1.2.0 (was 1.1.0)
  synchronized 3.0.0+3 (3.0.1 available)
  table_calendar 3.0.8 (3.0.9 available)
> term_glyph 1.2.1 (was 1.2.0)
> test_api 0.4.16 (was 0.4.9) (0.5.0 available)
  timeago 3.2.2 (3.4.0 available)
  url_launcher 6.1.5 (6.1.10 available)
  url_launcher_android 6.0.25 (6.0.26 available)
  url_launcher_ios 6.0.18 (6.1.3 available)
> vector_math 2.1.4 (was 2.1.2)
  win32 3.1.3 (4.1.1 available)
  xml 6.1.0 (6.2.2 available)
These packages are no longer being depended on:
- charcode 1.3.1
Changed 19 dependencies!
----- Getting version and build number from pubspec.yaml -----
Found 1.8.0+5 in pubspec.yaml
----- Creating export.plist file -----
----- Modifying XCode config -----
----- Pod install -----
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] CocoaPods could not find compatible versions for pod "Flutter":
  In Podfile:
    Flutter (from `Flutter`)

Specs satisfying the `Flutter (from `Flutter`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile.
See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error updating sources. Exit code 1
Build stop order received at 2023-03-27 15:17:47.116175+00:00

This command had been working well until today. Hope everyone could tell me what should i do.

**Comment by tchavetdeuse** [comment]
Hi, it looks like you have not specified a minimum deployment target, so version 9.0 was automatically assigned but it is too low for some dependencies. I see for example that you're using url_launcher, which requires version 11.0.
You can either configure the minimum deployment target in xcode with a configuration build, or by simply passing the parameter --minimum-ios-version 11.0 with the command appollo build start (or by adding minimum-ios-version=11.0 in a .appollo file so it is used for every build).
It seems to be a common error so we'll see what we can do to provide more info when it happens, or if we can automatically set the deployment target by looking at the dependencies
