### ISSUE TITLE
Very Slow 

### ISSUE THREAD

**Issue by Fatehroy** [Appollo-CLI/Appollo#26]

**Comment by maxcmoi89** [comment]
Not enough context.

**Comment by Fatehroy** [comment]
it's not stable, it's smooth but most of the time it's so slow till you can see the close animation when navigating

**Comment by maxcmoi89** [comment]
Thanks for the context. Can you tell me some more :
- Which country are you from ?
- What are your computer specs ? and which OS do you use ?
- Can you check the speed of your internet connection and paste it here ? https://fast.com/
- Which version of Appollo are you using ?
