### ISSUE TITLE
command "appollo" doesnt recognized on windows 10

### ISSUE THREAD

**Issue by rayanlevrai** [Appollo-CLI/Appollo#27]
I have installed appollo with "pip install appollo" in cmder (first time i use this) but when i call appollo with the command "apollo help" or something else argument, i cant... my windows can't call appollo.
I try too in cmd but same issue

Im beginner in code so sorry if my problem be stupid certainly.
sorry too for my english, im french ^^'

**Comment by tchavetdeuse** [comment]
Hi, it looks like the directory where pip packages are installed isn't in your PATH. To add it, search env in windows then choose "Edit the system environment variables", then in system variables find and edit Path and add the path to the directory where pip packages are installed (it should be in a scripts directory where python is installed)

**Comment by rayanlevrai** [comment]
Thank you for your answer ! the package was in this path:
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\

thank again.
