### ISSUE TITLE
How to Open Appollo in terminal

### ISSUE THREAD

**Issue by SaadRahim7** [Appollo-CLI/Appollo#31]
How I can open Appollo in my terminal 
 it always shows  " appollo: command not found
"

**Comment by Daphneyong11** [comment]
Did you install appollo first? Just run 'pip install appollo' and try 'appollo' command again.

**Comment by tchavetdeuse** [comment]
Hi, which OS are you using? You need to make sure that the directory where pip installs executables is included in your $PATH

**Comment by SaadRahim7** [comment]
Thanks for your replies it works
