### ISSUE TITLE
Forget password

### ISSUE THREAD

**Issue by Daphneyong11** [Appollo-CLI/Appollo#32]
I am having trouble login my appollo account. it keeps showing 'Unable to log in with provided credentials.' with any password that I can think of.
Maybe I did remember the wrong password, is there any way to reset my password?

Thank you in advance

**Comment by tchavetdeuse** [comment]
Hi, you can reset your password on the website: [https://appollo.space/user/password_reset/](url)

**Comment by Daphneyong11** [comment]
Thanks. Helps a lot.
