### ISSUE TITLE
Forgot password and email of my account

### ISSUE THREAD

**Issue by AndresArias09** [Appollo-CLI/Appollo#42]
Hi, hope everything is going well.

Recently i've tried to build a new ipa file for my app built in flutter, which in some point of this year I did this process with an specific account. Today, the only info that i remember of it is the user. I forgot both email and password. The problem is that i'm having the following error trying to add the same ios developer account to another apollo account:

Error: This developer account is already linked to user _'user'._ If you think this is a mistake, please contact
Appollo at hello@appollo.space

Is there any option to recover the password only with the user? if not, what should i do?

**Comment by tchavetdeuse** [comment]
Hi, can you please send an email with your username to hello@appollo.space? We will reply with the email associated to your username.
