### ISSUE TITLE
Annonce the time my Appollo Remote will be killed

### ISSUE THREAD

**Issue by TheToto42** [Appollo-CLI/Appollo#5]
I keep being surprised when my Apollo Remote is stopped.
It may be less surprising if the kill time is announced on the appollo configuration command.

Thanks for this amazing project !

**Comment by maxcmoi89** [comment]
Thank you for the suggestion. I think it would be a good addition. We will check if we can add it to our next release.

**Comment by maxcmoi89** [comment]
This feature has been added to v1.0.0
