### ISSUE TITLE
appollo build start is failed - Error: for Provisioning profile - Apple error: The relationship 'devices' is required but was not provided  with this request.

### ISSUE THREAD

**Issue by tickernelz** [Appollo-CLI/Appollo#6]
i got this error when i enter 'appollo build start '

```
 Error: for Provisioning profile - Apple error: The relationship 'devices' is required but was not provided 
with this request.
```
anyone know how to fix it?

**Comment by tchavetdeuse** [comment]
Hi,
Which type of build were you trying to launch ? If it is ad-hoc, Apple requires that you have at least one device registered on which you will be able to launch the generated ipa.
See [https://appollo.readthedocs.io/en/master/tutorial/7_create_ipa_testing_purpose.html#adding-your-device-to-apple-developer](url)

**Comment by TruFelix** [comment]
I have the same problem with build type configuration:
![image](https://github.com/Odevio/Odevio-CLI/assets/61414068/ef8392c3-953d-4ca7-99b0-623aaad0dd70)
