### ISSUE TITLE
appollo build start configuration error - The relationship 'devices' is required but was not provided with this request

### ISSUE THREAD

**Issue by T3chn0cr4t** [Appollo-CLI/Appollo#9]
when i start building i got the following error : 

` The relationship 'devices' is required but was not provided with this request`

ps : i tried all build types , same error

**Comment by maxcmoi89** [comment]
You shouldn't get this error with `-build-type configuration`.

This is an error if you have no devices on your Apple Developer Account: https://appollo.readthedocs.io/en/master/tutorial/7_create_ipa_testing_purpose.html#adding-your-device-to-apple-developer

It shouldn't cause an error in other types of builds. We will look into why it did not work with your account/appollo version.

**Comment by maxcmoi89** [comment]
Duplicate issue with : https://github.com/Appollo-CLI/Appollo/issues/6
